### ISSUE TITLE
Test with failure

### ISSUE THREAD

**Issue by Lili0820** [witnet/vrf-solidity#12]
I try to test the VRF verify by invoking the VRF contract with web3.py, but encounter the revoked error in ganache. I can't figure it out, maybe you know the cause？Thanks.

**Comment by mariocao** [comment]
Hi @Lili0820 ! 

We would need more information in order to try to help you out. :)
Could you provide the code that you are running and the error trace?

**Comment by Lili0820** [comment]
Thanks. I have solved it.
