### ISSUE TITLE
Performance improvement by user-provided CTR variable

### ISSUE THREAD

**Issue by aesedepece** [witnet/vrf-solidity#2]
The user could provide which CTR values provides a valid `H` EC point. As consequence the contract does not have to iterate until it finds a valid point.

**Comment by mariocao** [comment]
This improvement has to be assessed with caution as it is not clear that it does not raise some concerns about the malleability of VRFs.

**Comment by girazoki** [comment]
Closed because it is not clear that it completely secure (possible vulnerability in finding valid CTR values with lower hashes).
